ALTER TABLE STAGING.COLLATERAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE STAGING.COLLATERAL CASCADE CONSTRAINTS;

CREATE TABLE STAGING.COLLATERAL
(
  COLLATERAL_ID     NUMBER Generated as Identity ( START WITH 141 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  LOAN_ACCOUNT_ID   NUMBER                      NOT NULL,
  COLLATERAL_TYPE   VARCHAR2(50 BYTE),
  DESCRIPTION       VARCHAR2(200 BYTE),
  COLLATERAL_VALUE  NUMBER(15,2),
  APPRAISAL_DATE    DATE,
  STATUS            VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index STAGING.SYS_C007771.
--  The object is created when the parent object is created.

ALTER TABLE STAGING.COLLATERAL ADD (
  PRIMARY KEY
  (COLLATERAL_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MAXSIZE          UNLIMITED
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE STAGING.COLLATERAL ADD (
  CONSTRAINT FK_COLLATERAL_LOAN_ACCOUNT 
  FOREIGN KEY (LOAN_ACCOUNT_ID) 
  REFERENCES STAGING.LOAN_ACCOUNT (ACCOUNT_ID)
  ENABLE VALIDATE);
