ALTER TABLE STAGING.CUSTOMER
 DROP PRIMARY KEY CASCADE;

DROP TABLE STAGING.CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE STAGING.CUSTOMER
(
  CUSTOMER_ID    NUMBER,
  NAME           VARCHAR2(100 BYTE),
  EMAIL          VARCHAR2(100 BYTE),
  PHONE          VARCHAR2(20 BYTE),
  BRANCH_ID      NUMBER,
  CREATE_DATE    DATE,
  COLLATERAL_ID  NUMBER,
  STATUS         VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index STAGING.SYS_C007759.
--  The object is created when the parent object is created.

ALTER TABLE STAGING.CUSTOMER ADD (
  PRIMARY KEY
  (CUSTOMER_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MAXSIZE          UNLIMITED
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE STAGING.CUSTOMER ADD (
  CONSTRAINT FK_CUSTOMER_COLLATERAL 
  FOREIGN KEY (COLLATERAL_ID) 
  REFERENCES STAGING.COLLATERAL (COLLATERAL_ID)
  ENABLE VALIDATE);
