ALTER TABLE STAGING.LOAN_ACCOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE STAGING.LOAN_ACCOUNT CASCADE CONSTRAINTS;

CREATE TABLE STAGING.LOAN_ACCOUNT
(
  ACCOUNT_ID          NUMBER,
  OFFICER_ID          NUMBER,
  LOAN_AMOUNT         NUMBER(12,2),
  INTEREST_RATE       NUMBER(5,2),
  LOAN_TERM_MONTHS    NUMBER,
  START_DATE          DATE,
  MATURITY_DATE       DATE,
  PRINCIPAL_BAL       NUMBER(12,2),
  ACCRUED_INTEREST    NUMBER(15),
  TOTAL_INTEREST      NUMBER(15),
  APPLICATION_AMOUNT  NUMBER(12,2)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index STAGING.SYS_C007758.
--  The object is created when the parent object is created.

ALTER TABLE STAGING.LOAN_ACCOUNT ADD (
  PRIMARY KEY
  (ACCOUNT_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MAXSIZE          UNLIMITED
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE STAGING.LOAN_ACCOUNT ADD (
  FOREIGN KEY (ACCOUNT_ID) 
  REFERENCES STAGING.ACCOUNT (ACCOUNT_ID)
  ENABLE VALIDATE,
  FOREIGN KEY (OFFICER_ID) 
  REFERENCES STAGING.LOAN_OFFICER (OFFICER_ID)
  ENABLE VALIDATE);
