DROP TABLE STAGING.REPAYMENT_SCHEDULE CASCADE CONSTRAINTS;

CREATE TABLE STAGING.REPAYMENT_SCHEDULE
(
  LOAN_ACCOUNT_ID   NUMBER                      NOT NULL,
  DUE_DATE          DATE                        NOT NULL,
  PRINCIPAL_AMOUNT  NUMBER(15,2)                NOT NULL,
  INTEREST_AMOUNT   NUMBER(15,2)                NOT NULL,
  STATUS            VARCHAR2(20 BYTE)           DEFAULT 'PENDING',
  PAYMENT_DATE      DATE,
  AMOUNT_DUE        NUMBER(15,2)                NOT NULL,
  PAYMENT_NUMBER    NUMBER(15,2),
  DAYS_PAST_DUE     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE INDEX STAGING.IDX_REPAYMENT_LOAN_DUE ON STAGING.REPAYMENT_SCHEDULE
(LOAN_ACCOUNT_ID, DUE_DATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE STAGING.REPAYMENT_SCHEDULE ADD (
  CHECK (status IN ('PENDING', 'PAID', 'PARTIAL', 'OVERDUE'))
  ENABLE VALIDATE);
