ALTER TABLE STAGING.ACH_TRANSACTION_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE STAGING.ACH_TRANSACTION_CODE CASCADE CONSTRAINTS;

CREATE TABLE STAGING.ACH_TRANSACTION_CODE
(
  TRANSACTION_CODE            VARCHAR2(5 BYTE),
  TRANSACTION_NAME            VARCHAR2(50 BYTE) NOT NULL,
  TRANSACTION_CATEGORY        VARCHAR2(20 BYTE) NOT NULL,
  DIRECTION                   VARCHAR2(10 BYTE) NOT NULL,
  DESCRIPTION                 VARCHAR2(200 BYTE) NOT NULL,
  NACHA_STANDARD_ENTRY_CLASS  VARCHAR2(3 BYTE),
  IS_SAME_DAY_ELIGIBLE        CHAR(1 BYTE)      DEFAULT 'N',
  EFFECTIVE_DATE              DATE              DEFAULT SYSDATE,
  EXPIRATION_DATE             DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE STAGING.ACH_TRANSACTION_CODE IS 'Reference table for all standard ACH transaction types and codes';

COMMENT ON COLUMN STAGING.ACH_TRANSACTION_CODE.NACHA_STANDARD_ENTRY_CLASS IS 'NACHA Standard Entry Class code';

COMMENT ON COLUMN STAGING.ACH_TRANSACTION_CODE.IS_SAME_DAY_ELIGIBLE IS 'Y if eligible for Same-Day ACH processing';


--  There is no statement for index STAGING.SYS_C007875.
--  The object is created when the parent object is created.

ALTER TABLE STAGING.ACH_TRANSACTION_CODE ADD (
  CHECK (DIRECTION IN ('DEBIT', 'CREDIT', 'BOTH'))
  ENABLE VALIDATE,
  CHECK (IS_SAME_DAY_ELIGIBLE IN ('Y', 'N'))
  ENABLE VALIDATE,
  PRIMARY KEY
  (TRANSACTION_CODE)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MAXSIZE          UNLIMITED
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
