ALTER TABLE STAGING.COUNTRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE STAGING.COUNTRY CASCADE CONSTRAINTS;

CREATE TABLE STAGING.COUNTRY
(
  COUNTRY_ID                  NUMBER Generated as Identity ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  COUNTRY_CODE                VARCHAR2(5 BYTE)  NOT NULL,
  COUNTRY_NAME                VARCHAR2(100 BYTE) NOT NULL,
  INTERNATIONAL_DIALING_CODE  VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


--  There is no statement for index STAGING.SYS_C007983.
--  The object is created when the parent object is created.

ALTER TABLE STAGING.COUNTRY ADD (
  PRIMARY KEY
  (COUNTRY_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MAXSIZE          UNLIMITED
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
