ALTER TABLE STAGING.EXT_BANK_ACCOUNTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE STAGING.EXT_BANK_ACCOUNTS CASCADE CONSTRAINTS;

CREATE TABLE STAGING.EXT_BANK_ACCOUNTS
(
  ACCOUNT_ID            NUMBER(30)              NOT NULL,
  CUSTOMER_ID           NUMBER(30)              NOT NULL,
  BANK_NAME             VARCHAR2(50 BYTE)       NOT NULL,
  BANK_ROUTING_NUMBER   VARCHAR2(9 BYTE)        NOT NULL,
  ACCOUNT_NUMBER_LAST4  VARCHAR2(4 BYTE)        NOT NULL,
  ACCOUNT_TYPE          VARCHAR2(20 BYTE)       NOT NULL,
  ACCOUNT_NICKNAME      VARCHAR2(50 BYTE),
  IS_PRIMARY_ACCOUNT    CHAR(1 BYTE)            DEFAULT 'N',
  VERIFICATION_STATUS   VARCHAR2(20 BYTE)       DEFAULT 'UNVERIFIED',
  DATE_ADDED            DATE                    DEFAULT SYSDATE,
  DATE_VERIFIED         DATE,
  ACH_ENABLED           CHAR(1 BYTE)            DEFAULT 'Y',
  EXT_BANK_ACCOUNT_ID   NUMBER(30)              NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE STAGING.EXT_BANK_ACCOUNTS IS 'Stores bank account information for ACH transactions';

COMMENT ON COLUMN STAGING.EXT_BANK_ACCOUNTS.ACCOUNT_ID IS 'Reference to internal account system (foreign key)';

COMMENT ON COLUMN STAGING.EXT_BANK_ACCOUNTS.BANK_ROUTING_NUMBER IS 'ABA routing number (9 digits)';

COMMENT ON COLUMN STAGING.EXT_BANK_ACCOUNTS.ACCOUNT_NUMBER_LAST4 IS 'Last 4 digits of account number for display';

COMMENT ON COLUMN STAGING.EXT_BANK_ACCOUNTS.VERIFICATION_STATUS IS 'Status of micro-deposit verification process';

COMMENT ON COLUMN STAGING.EXT_BANK_ACCOUNTS.EXT_BANK_ACCOUNT_ID IS 'Primary key for external bank accounts table';


CREATE INDEX STAGING.IDX_BANK_CUSTOMER ON STAGING.EXT_BANK_ACCOUNTS
(CUSTOMER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX STAGING.IDX_BANK_ROUTING ON STAGING.EXT_BANK_ACCOUNTS
(BANK_ROUTING_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX STAGING.IDX_BANK_VERIFIED ON STAGING.EXT_BANK_ACCOUNTS
(VERIFICATION_STATUS)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX STAGING.PK_EXT_BANK_ACCOUNTS ON STAGING.EXT_BANK_ACCOUNTS
(EXT_BANK_ACCOUNT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE STAGING.EXT_BANK_ACCOUNTS ADD (
  CHECK (ACCOUNT_TYPE IN ('CHECKING', 'SAVINGS', 'MONEY_MARKET', 'BUSINESS_CHECKING'))
  ENABLE VALIDATE,
  CHECK (IS_PRIMARY_ACCOUNT IN ('Y', 'N'))
  ENABLE VALIDATE,
  CHECK (VERIFICATION_STATUS IN ('VERIFIED', 'UNVERIFIED', 'PENDING', 'REJECTED'))
  ENABLE VALIDATE,
  CHECK (ACH_ENABLED IN ('Y', 'N'))
  ENABLE VALIDATE,
  CONSTRAINT PK_EXT_BANK_ACCOUNTS
  PRIMARY KEY
  (EXT_BANK_ACCOUNT_ID)
  USING INDEX STAGING.PK_EXT_BANK_ACCOUNTS
  ENABLE VALIDATE);

ALTER TABLE STAGING.EXT_BANK_ACCOUNTS ADD (
  CONSTRAINT FK_BANK_CUSTOMER 
  FOREIGN KEY (CUSTOMER_ID) 
  REFERENCES STAGING.CUSTOMER (CUSTOMER_ID)
  ENABLE VALIDATE);
